Fee pooling SDK change
algorand/go-algorand-sdk pull request #216
Opened 2021-06-15 18:14 UTC by shiqizng

This PR is to support creating transactions with a fee under mintxnfee since other txns in the group will be paying.

2021-06-16 14:42 UTC, jdtzmn requested changes
Mostly looks good - I just left one comment. Can you also add a test case that explicitly sets the fee to 0?

2021-06-16 14:42 UTC, jdtzmn commented on future/transaction_test.go
> +			name:     "Flat fee does not overridden with min fee",
nit: _is not_ or _does not get_

2021-06-16 22:49 UTC, jasonpaulos requested changes
Implementation looks good, but could you modify the descriptions for the `SuggestedParams` struct? Specifically:
* For `Fee`, it current says "Fee may fall to zero but transactions must still have a fee of at least MinTxnFee for the current network protocol." Maybe change this to "Fee may fall to zero but a group of N atomic transactions must still have a fee of at least N*MinTxnFee for the current network protocol."
* For `FlatFee`, mention that if this is true, the fee is not guaranteed to be above the network minimum.

2021-06-17 14:19 UTC, jasonpaulos approved these changes
Looks good! Thanks for making the requested changes

2021-06-17 14:26 UTC, winder commented on types/transaction.go
> +	// still have a fee of at least N*MinTxnFee for the current network protocol.
Might be nice to check the minimum balance in `crypto.ComputeGroupID`

2021-06-17 15:23 UTC, jdtzmn requested changes

2021-06-17 15:23 UTC, jdtzmn commented on types/transaction.go
> +	// If true, txn fee is may fall below the MinTxnFee for the current network protocol.
nit: txn fee _may_ fall

2021-06-17 15:32 UTC, jdtzmn approved these changes

2021-06-17 16:31 UTC, merged