bug-fix: include currency-greater-than param for 0 value
algorand/go-algorand-sdk pull request #584
Opened 2023-08-07 20:13 UTC by shiqizng

This PR fixes #583

2023-08-07 20:14 UTC, shiqizng commented on .test-env
> +SDK_TESTING_BRANCH="shiqi/pathupdates"
TODO: update branch to V2 before merge.

2023-08-08 13:36 UTC, algochoi approved these changes
Looks good but let's revert to main testing branch before merge

2023-08-10 15:07 UTC, tzaffi approved these changes
lgtm

2023-08-10 15:35 UTC, winder requested changes
This is generated code, so there needs to be a corresponding change here: https://github.com/algorand/generator/

2023-08-10 19:53 UTC, shiqizng commented
Ran the generator. Included all the updated files.

2023-08-10 20:19 UTC, winder approved these changes

2023-08-10 20:49 UTC, bbroder-algo approved these changes

2023-08-10 21:07 UTC, merged